---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'happ'

SiteConfig:
  extensions:
    - EventFindaExtension
    - HappSiteConfig


FulltextSearchable:
  searchable_classes:
    - 'SiteTree'
SiteTree:
  create_table_options:
    MySQLDatabase:
      'ENGINE=MyISAM'
  extensions:
    - MyISAMExtension
    - "FulltextSearchable('Title, MenuTitle, Content, MetaDescription')"

DataObject:
  extensions:
    - MyISAMExtension

Event:
  extensions:
    - MyISAMExtension

File:
  extensions:
    - MyISAMExtension